### ISSUE TITLE
No support for Partner Connection

### ISSUE THREAD

**Issue by chrisrichard** [davispeixoto/Laravel-4-Salesforce#10]
> IMPORTANT: the PHP Force.com Toolkit for PHP only works with Enterprise WSDL

I was able to use it successfully on a different (non-Laravel) project. Would rather integrate your wrapper on this one but need to use partner connection.

Note that you need to use a SforcePartnerClient object rather than SforceEnterpriseClient.

**Comment by chrisrichard** [comment]
Also a different data interface when using Partner client, geard toward KV access:

 $lead = new SObject();
 $lead->type = 'Lead';
 $lead->fields = ['Name' => '...', 'Phone' => '...', ...];

**Comment by davispeixoto** [comment]
Thanks for this information. However, I'm thinking about the stability of application using the partner client.

I'm not sure if it is stable enough.

**Comment by davispeixoto** [comment]
Hey, Chris. You can create a pull request, updating the documentation. What does it sound for you?
