### ISSUE TITLE
Laravel 5 Compatibility

### ISSUE THREAD

**Issue by etelford** [davispeixoto/Laravel-4-Salesforce#9]
I've forked your Laravel 4 package and updated for Laravel 5. I'd be happy to create a pull request and make the same updates to your package if you'd like.

https://github.com/etelford/Laravel-5-Salesforce

**Comment by davispeixoto** [comment]
Hi Erik,

thanks for your work.

I was aiming to make the Laravel 5 Package as soon as L5 gets a stable release.

However, I never intended to make L5 package be an extension of L4, but a new package designed to L5 and built upon Force.com Toolkit. Thus, any programmer that is using the current package with some malformed composer.json won't be affected, and anyone diving into L5 would have a good package to work with.

Thanks again in the community name, but I think I will fork your package :)

**Comment by etelford** [comment]
Sounds great. 

I'm in the middle of adding a fluent interface to writing SOQL. I'll let you know when that's finished.
